{
    'name' : 'Asterisk Dialer',
    'description': '',
    'summary': 'Telemarketing, Partners, Phone lists, Statistics',
    'version' : '1.1',
    'depends' : ['base', 'mail', 'web',],
    'author' : 'litnimax',
    'website' : '',
    'category' : 'Asterisk',
    'data' : [
        'views/assets.xml',
        'security/security.xml', 
        'security/ir.model.access.csv',        
        'views/dialer_view.xml',
        'views/dialer_data.xml',
        'views/server_view.xml',
        'views/server_data.xml',
        'views/partner_search.xml',
        'views/soundfile_view.xml',
    ],
    'js': ['static/src/js/*.js'],
    'qweb': ['static/src/xml/*.xml'], 
    'auto_install': False,
    'installable': True,
    'application': True,
}
